// C4D-DialogResource
DIALOG DLG_OPTIONS
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    SCALE_V; SCALE_H; 
    BORDERSIZE 8, 8, 8, 8; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS EDT_HSPACE
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS EDT_VSPACE
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC3; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      
    }
    BUTTON BTN_SAVE { NAME IDS_BUTTON; ALIGN_TOP; ALIGN_RIGHT; }
  }
}